### ISSUE TITLE
no tel: link displayed in contacts menu/app

### ISSUE THREAD

**Issue by j-ed** [georgehrke/nextcloud-telephoneProvider#2]
## Expected behavior
The app should provide a link next to a phone number to initiate dialing.

## Current behavior
Unfortunately a link cannot be found in the contacts menu to initiate dialing of a phone number.

### Steps to reproduce
1. Open the Contacts app
   -> No link is displayed to initiate dialing.

#### Server Configuration
OS: Linux 3.16.42
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 12.0.0
Contacts app version: 1.5.3

#### Client Configuration
Browser: Mozilla Firefox 54.0.0
Operating system: Windows 7

**Comment by adsworth** [comment]
The link only appears in Nextcloud 12 the contacts menu on the top between the search field and the settings menu.

**Comment by j-ed** [comment]
@georgehrke Thank you, I though I would find a button behind a phone number field. I've created a screenshot of the function to ease finding it:
![20170621_kontakt_menu](https://user-images.githubusercontent.com/2572764/27384989-52c967ce-5691-11e7-8f65-d65de56b5522.png)
