### ISSUE TITLE
add a settings dialog to influence the phone number formatting

### ISSUE THREAD

**Issue by j-ed** [georgehrke/nextcloud-telephoneProvider#3]
## Expected behavior
The app should allow to define some kind of dialing rules to parse a phone number in the right format to 
a dial program. If you're e.g. located in Duesseldorf, Germany the country code is `49` and the area code is `211`.
- If you dial a number in London and the contact record contains `+44 20 ...` it should be possible to change it to `0044 20 ...`.
- If you dial a number in Frankfurt, Germany and the contact record contains `+49 69 ...` it should be possible to change it to `069 ...`.
- If you dial a number in Duesseldorf, Germany and the contact record contains `+49 211 33...` it should be possible to change it to `33...`.
Summarized it should be possible to enter the country and area code and information about character/number replacements.

## Current behavior
There are no setting available to influence the dialing process yet.

### Steps to reproduce
1. Open the contacts function in the menu bar.
2. Select a phone number which has been written in international format, e.g. `+49 ...`
3. The dialing will fail if e.g. the Windows dialer program is used because it cannot handle phone numbers in this format correctly.

#### Server Configuration
OS: Linux 3.16.42
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 12.0.0
Contacts app version: 1.5.3

#### Client Configuration
Browser: Mozilla Firefox 54.0.0
Operating system: Windows 7

**Comment by georgehrke** [comment]
We already strip anything that's not a + or a number.
So if you see `Call +49 (211) 123 456 78`, the generated link will be `+4921112345678`.
If Windows can't handle + in a phone number, I consider this a bug in windows.

**Comment by georgehrke** [comment]
> If you dial a number in Frankfurt, Germany and the contact record contains +49 69 ... it should be possible to change it to 069 ....

It's not possible for us to know that the Nextcloud user (who initiates the call) has a phone number with the country code +49.

And your telephone provider won't charge you more, whether you dial `+4969` or `069`

**Comment by georgehrke** [comment]
> Summarized it should be possible to enter the country and area code and information about character/number replacements.

Won't fix. Region codes change from country to country. We would have to create a list about all countries and how their telephone numbers are structured. And we would have to keep that list up to date.

All while just entering the entire phone number with +49... is just equally valid.

**Comment by georgehrke** [comment]
Also see https://en.wikipedia.org/wiki/List_of_international_call_prefixes#Example

The + leaves it up for the program making the actual call to determine the correct trunk prefix.

**Comment by georgehrke** [comment]
btw, this app doesnt add anything like `+49`. It just takes the phone number straight from your address book. So if you only enter `069` for a contact in your address book, the generated telephone link will start with `069`, not `+4969`

**Comment by j-ed** [comment]
> Won't fix. Region codes change from country to country. We would have to create a list about all countries and how their telephone numbers are structured. And we would have to keep that list up to date.

This would only be the case if you want to control the input of a field. It wouldn't be necessary to know all phone numbers or area codes except the ones of your own location, if you only create to input fields
This is the way many other programs doing the job.

> The + leaves it up for the program making the actual call to determine the correct trunk prefix.

Ok, that's the way I solved it for the moment. I've written a vbs wrapper script to replace an existing `'+'` sign by `'00'` and parse the resulting string to the dial.exe program.

BTW: If you click on a phone number link using Firefox 54.0 (I don't know if it matters) the string which is parsed to an external program is `'tel://+4921112345678/'` and not only the number `'+4921112345678'`.
