### ISSUE TITLE
Generated telephone URIs do not work in Firefox 56

### ISSUE THREAD

**Issue by 9662** [georgehrke/nextcloud-telephoneProvider#4]
This application generates URIs like `tel://+123456789`, which are not strictly compliant with [RFC3966](https://tools.ietf.org/html/rfc3966) and seem to fail in Firefox 56, which gives a "server not found" error after re-interpreting the URL as `tel//+123456789` (note the missing colon).

URIs of the form `tel:+123456789` do work, in my case resulting in [KDE Connect](https://community.kde.org/KDEConnect)'s dialler being called.

**Comment by georgehrke** [comment]
Fix is in #5

**Comment by georgehrke** [comment]
I published a new version on the Nextcloud App Store fixing this bug.

**Comment by 9662** [comment]
Works a charm now. Thanks! ☺
