### ISSUE TITLE
Nextcloud 14 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [georgehrke/nextcloud-telephoneProvider#7]
Hey @georgehrke,

please see https://github.com/orgs/nextcloud/projects/15#card-11847045 :wink:

Cheers

**Comment by georgehrke** [comment]
@ChristophWurst Is there any particular issue with the app or do you just want me to make sure everything works fine? :)

**Comment by ChristophWurst** [comment]
> or do you just want me to make sure everything works fine? :)

That :) If the app works please just move the card to "Done" :wink:

**Comment by georgehrke** [comment]
Works on 14 and 15 👍
